from enum import Enum
from typing import NamedTuple

from config.prompts import (
    FINANCIAL_DATA_SYSTEM_PROMPT,
    GENERATE_DEEP_RESEARCHED_CONTENT_SYSTEM_PROMPT,
    GENERATE_EVENT_TITLE_SYSTEM_PROMPT,
    GENERATE_SUMMARIZED_CONTENT_FROM_DEEP_RESEARCH_SYSTEM_PROMPT,
    GET_COMPLIANCE_CHECK_SYSTEM_PROMPT,
    GET_PRIORITY_FLAG_SYSTEM_PROMPT,
    GET_SENTIMENTAL_ANALYSIS_SYSTEM_PROMPT,
    REVISING_FINANCIAL_CONTENT_WITH_TONE_CONTROL_USER_PROMPT,
)


class GetTimeRangeResponseDTO(NamedTuple):
    """
    Data Transfer Object for GetTimeRangeResponse.
    """

    time_from: str
    time_to: str


class PromptEnum(str, Enum):
    """
    Enum for available prompts.
    """

    FINANCIAL_DATA_SYSTEM_PROMPT = FINANCIAL_DATA_SYSTEM_PROMPT
    GENERATE_EVENT_TITLE_SYSTEM_PROMPT = GENERATE_EVENT_TITLE_SYSTEM_PROMPT
    GENERATE_DEEP_RESEARCHED_CONTENT_SYSTEM_PROMPT = (
        GENERATE_DEEP_RESEARCHED_CONTENT_SYSTEM_PROMPT
    )
    GENERATE_SUMMARIZED_CONTENT_FROM_DEEP_RESEARCH_SYSTEM_PROMPT = (
        GENERATE_SUMMARIZED_CONTENT_FROM_DEEP_RESEARCH_SYSTEM_PROMPT
    )
    GET_SENTIMENTAL_ANALYSIS_SYSTEM_PROMPT = GET_SENTIMENTAL_ANALYSIS_SYSTEM_PROMPT
    GET_PRIORITY_FLAG_SYSTEM_PROMPT = GET_PRIORITY_FLAG_SYSTEM_PROMPT
    GET_COMPLIANCE_CHECK_SYSTEM_PROMPT = GET_COMPLIANCE_CHECK_SYSTEM_PROMPT
    REVISING_FINANCIAL_CONTENT_WITH_TONE_CONTROL_USER_PROMPT = (
        REVISING_FINANCIAL_CONTENT_WITH_TONE_CONTROL_USER_PROMPT
    )


class WebsocketMessageTypesEnum(str, Enum):
    """
    Enum for available websocket message types.
    """

    LIVE_EVENTS = "live_events"
    USER_CUSTOM_EVENT = "user_custom_event"
