FINANCIAL_DATA_SYSTEM_PROMPT = """"""

GENERATE_EVENT_TITLE_SYSTEM_PROMPT = ""

GENERATE_DEEP_RESEARCHED_CONTENT_SYSTEM_PROMPT = ""

GENERATE_SUMMARIZED_CONTENT_FROM_DEEP_RESEARCH_SYSTEM_PROMPT = ""

GET_SENTIMENTAL_ANALYSIS_SYSTEM_PROMPT = ""
