"""Updated enums field into model

Revision ID: b9e455ba8931
Revises: bc08239b3cd2
Create Date: 2025-05-16 11:14:31.230177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e455ba8931'
down_revision: Union[str, None] = 'bc08239b3cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE poststatus ADD VALUE 'APPROVED';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
