"""Initial migrations

Revision ID: bc08239b3cd2
Revises:
Create Date: 2025-04-25 20:46:40.335660

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc08239b3cd2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("banner", sa.String(), nullable=True),
        sa.Column(
            "sentimental_analysis",
            sa.Enum("POSITIVE", "NEGATIVE", "NEUTRAL", name="sentimentalanalysis"),
            nullable=True,
        ),
        sa.Column(
            "priority_flag",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="priorityflag"),
            nullable=True,
        ),
        sa.Column("compliance_check", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("deep_research_content", sa.String(), nullable=True),
        sa.Column("ai_generated_summarized_content", sa.String(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "RESEARCHING",
                "WRITING",
                "FETCHING_ANALYTICS",
                "DRAFTED",
                "FAILED",
                name="marketevenprocessingtstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "ALPHA_VANTAGE_API",
                "EVENT_REGISTRY_API",
                "CUSTOM_EVENT",
                name="marketeventsource",
            ),
            nullable=False,
        ),
        sa.Column("is_customized", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("market_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.Enum("DRAFT", "PUBLISHED", name="poststatus"), nullable=False
        ),
        sa.Column("is_customized", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_event_id"],
            ["market_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("users")
    op.drop_table("market_events")
    # ### end Alembic commands ###
