name: Deployment Staging

on:
  push:
    branches:
      - development

jobs:
  build-staging:
    runs-on:
      - self-hosted
      - staging

    defaults:
      run:
        working-directory: /home/ubuntu/backend/actions-runner/_work/finance-agent-backend/finance-agent-backend

    steps:

      - name: Ensure consistent file permissions
        run: |
          sudo chown -R $USER:$USER /home/ubuntu/backend/actions-runner/_work/finance-agent-backend/finance-agent-backend
          
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env.stg to .env
        run: |
          echo "Copying environment variables for staging..."
          cp /home/ubuntu/backend/.env.stg /home/ubuntu/backend/actions-runner/_work/finance-agent-backend/finance-agent-backend
  
      - name: Remove dangling Docker images
        run: |
          echo "Pruning unused Docker resources (images, containers)..."
          docker image prune -f
          docker container prune -f

      - name: Build and Run Docker Compose
        run: |
          echo "Running Docker Compose in staging environment..."
          ENVIRONMENT=stg docker compose up -d --build
